Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 12/06/2024
Var
   i, numero:inteiro

Inicio
   escreva( "Digite um numero ")
   leia (numero)
   i <- 1
   enquanto i <= 10 faca
      escreval( i:2 , " x  " , numero , " = " , i * numero:3)
      i := i + 1
   fimenquanto
Fimalgoritmo